[workspace]
members = [
    "crates/rustc_codegen_spirv",
    "crates/spirv-builder",
    "crates/spirv-std",
    "examples/example-runner-cpu",
    "examples/example-runner",
    "examples/wgpu-example-runner",
    "examples/example-shader",
    "examples/wgpu-example-shader",
]
